FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get install -y --no-install-recommends clang make gnustep-devel libgnustep-gui-dev libsqlite3-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /work
CMD ["/bin/bash", "-lc", "cp -a /src /work/MacBasic && cd /work/MacBasic && . /usr/share/GNUstep/Makefiles/GNUstep.sh && make -f Makefile clean && make -f Makefile && test -x build/MacBasic.app/MacBasic && test -f build/MacBasic.app/Resources/Info-gnustep.plist && make -f Makefile test"]
